# Module One Homework

#### By Chinonso Okonkwo 
#### To MLZoomcamp2025

In [2]:
import numpy as np
import pandas as pd

Q1. Pandas version <br>
What version of Pandas did you install?<br>

You can get the version information using the __version__ field:

In [4]:
pd.__version__

'2.3.1'

In [23]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [24]:
df.shape

(9704, 11)

Q2. Records count <br>
How many records are in the dataset?

In [25]:
num = df.shape[0]
print(f"There are {num} number of records")

There are 9704 number of records

Q3. Fuel types <br>
How many fuel types are presented in the dataset?

In [26]:
df.fuel_type.value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   engine_displacement  9704 non-null   int64
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64
 6   origin               9704 non-null   object
 7   fuel_type            9704 non-null   object
 8   drivetrain           9704 non-null   object
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB

Q4. Missing  <br>
How many columns in the dataset have missing values?

In [28]:
df.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

Q5. Max fuel efficiency <br>
What's the maximum fuel efficiency of cars from Asia?

In [29]:
df[df['origin'] == 'Asia'].describe()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,3247.000000,3099.000000,3013.000000,3247.000000,2933.000000,3247.000000,3072.000000,3247.000000
mean,200.052356,4.010326,150.303352,3006.292228,15.036754,2011.489375,-0.001628,14.973830
std,49.287252,1.971199,30.257169,502.434626,2.488340,6.704607,1.051428,2.578345
min,30.000000,0.000000,40.000000,1223.298226,6.400000,2000.000000,-4.000000,6.886245
25%,170.000000,3.000000,130.000000,2665.518985,13.300000,2006.000000,-1.000000,13.252010
50%,200.000000,4.000000,150.000000,2988.585737,15.100000,2012.000000,0.000000,15.034670
75%,230.000000,5.000000,171.000000,3345.355571,16.700000,2017.000000,1.000000,16.726318
max,370.000000,11.000000,245.000000,4661.144932,22.700000,2023.000000,4.000000,23.759123

In [30]:
df.describe()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,9704.000000,9222.000000,8996.000000,9704.000000,8774.000000,9704.000000,9202.000000,9704.000000
mean,199.708368,3.962481,149.657292,3001.280993,15.021928,2011.484027,-0.006412,14.985243
std,49.455319,1.999323,29.879555,497.894860,2.510339,6.659808,1.048162,2.556468
min,10.000000,0.000000,37.000000,952.681761,6.000000,2000.000000,-4.000000,6.200971
25%,170.000000,3.000000,130.000000,2666.248985,13.300000,2006.000000,-1.000000,13.267459
50%,200.000000,4.000000,149.000000,2993.226296,15.000000,2012.000000,0.000000,15.006037
75%,230.000000,5.000000,170.000000,3334.957039,16.700000,2017.000000,1.000000,16.707965
max,380.000000,13.000000,271.000000,4739.077089,24.300000,2023.000000,4.000000,25.967222

Q6. Median value of horsepower <br>
Find the median value of the horsepower column in the dataset.<br>
Next, calculate the most frequent value of the same horsepower column.<br>
Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.<br>
Now, calculate the median value of horsepower once again.<br>
Has it changed?<br>

Yes, it increased<br>
Yes, it decreased<br>
No

In [31]:
df['horsepower'].median()

np.float64(149.0)

In [32]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [33]:
df['horsepower'].mode().iloc[0]

np.float64(152.0)

In [34]:
df['horsepower'].value_counts()

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ...
40.0       1
57.0       1
245.0      1
252.0      1
61.0       1
Name: count, Length: 192, dtype: int64

In [35]:
df['horsepower'].fillna(df['horsepower'].mode().iloc[0], inplace = True)

/tmp/ipykernel_22870/4041676216.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(df['horsepower'].mode().iloc[0], inplace = True)

In [36]:
df['horsepower'].median()

np.float64(152.0)

Q7. Sum of weights <br>
Select all the cars from Asia <br>
Select only columns vehicle_weight and model_year <br>
Select the first 7 values <br>
Get the underlying NumPy array. Let's call it X.<br>
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.<br>
Invert XTX.<br>
Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].<br>
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.<br>
What's the sum of all the elements of the result?

In [37]:
df_asia = df[df['origin'] == 'Asia']

In [38]:
df_asia.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
8,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554
12,320,5.0,145.0,2783.868974,15.1,2010,Asia,Diesel,All-wheel drive,1.0,16.175820
14,200,6.0,160.0,3582.687368,14.9,2007,Asia,Diesel,All-wheel drive,0.0,11.871091
20,150,3.0,197.0,2231.808142,18.7,2011,Asia,Gasoline,Front-wheel drive,1.0,18.889083
21,160,4.0,133.0,2659.431451,NaN,2016,Asia,Gasoline,Front-wheel drive,-1.0,16.077730

In [39]:
df_asia[['vehicle_weight', 'model_year']]

      vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [43]:
df_asia[['vehicle_weight', 'model_year']].iloc[0:7]

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [44]:
X = df_asia[['vehicle_weight', 'model_year']].iloc[0:7].to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [47]:
transpose = X.T
transpose

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [48]:
XTX = np.dot(transpose , X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [49]:
inv = np.linalg.inv(XTX)
inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [54]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y.dtype

dtype('int64')

In [56]:
temp = np.dot(inv, transpose)
w = np.dot(temp, y)
w

array([0.01386421, 0.5049067 ])

In [57]:
w.sum()

np.float64(0.5187709081074016)